### ISSUE TITLE
Feature Request -Reuse last location

### ISSUE THREAD

**Issue by GallaherMike** [gyng/save-in#20]
Have a shortcut (double click, alt+click, etc) to save a resource to the last location used.

**Comment by Skyleaf** [comment]
I would like to second this. I'm coming from Save Image In Folder and frequently used the ability to double left OR right click to save an image to the last location. Double clicking is nice and quick when going through many images, though support for both left and right mouse buttons would be great, since double left clicking an image that's also a link gets annoying pretty quickly.

**Comment by mageta** [comment]
I would second that as well. This was one of the most used features in downthem all for me personally. Specify a download-location and then quickly reuse it in pretty much one click via context menu.

**Comment by gyng** [comment]
I'm open to implementing this, ideally through a new menu item and keyboard shortcuts (#15). I really don't want to add event listeners to pages.

**Comment by gyng** [comment]
It's not the same, but there's now a "last used" at the top of the context menu in 1.5.0. It will be much better if/when keyboard shortcuts for context menus arrive in Firefox.

**Comment by Sjkomy** [comment]
I am so waiting for this option (moved from save in folder)  it consumes a lot if time to open context menu each time, hope soon it will be implemented, all that art and hentai won't download by itself! )

**Comment by gyng** [comment]
I've added this as an experimental option in 2.2.0.

https://github.com/gyng/save-in/issues/15#issuecomment-353930318

**Comment by gyng** [comment]
I assume the issue's been resolved. Please reopen otherwise.
