### ISSUE TITLE
Unable to save to paths longer than 18 characters after update to version 3.7.0

### ISSUE THREAD

**Issue by gtsaf0** [gyng/save-in#200]
Hello

This started to happen on the new version.
The message that shows on Firefox console is: "browser.ui.interaction.content_context - The key length must be limited to 72 characters."
Path I'm trying to write to is 22 characters long,  44 characters long with the filename and the file extension.

Thanks

**Comment by gyng** [comment]
I can't replicate this, do you have an example I can try?

**Comment by gyng** [comment]
I've released 3.7.1 with some refactors to menu creation. I can't really tell if that fixes this issue (hopefully without creating new bugs).

**Comment by gtsaf0** [comment]
> I've released 3.7.1 with some refactors to menu creation. I can't really tell if that fixes this issue (hopefully without creating new bugs).

This seems to have fixed it, many thanks.

**Comment by gtsaf0** [comment]
> I can't replicate this, do you have an example I can try?
Here is a snippet of my menu
.
---
pics
pics/cat // (alias: cat)
>pics\cat // (alias: general)
>pics\cat\white // (alias: white) 

The default path is on a drive different than the default Windows path, so D:\Downloads
If it is related, the target of the symlink has a space and a '&' in its path.

**Comment by seth-rah** [comment]
Having issues saving here on Chrome as well since updating to 3.7.0

No errors being collected on Chrome, but I can only save to default folder. Any saves to the folders through a symlink just result in no function being performed (at least visually)

**Comment by gyng** [comment]
Hey, I tried with more test cases and a symlink and I still can't replicate on Windows/FF111.0a1 or Chromium/112.0.5581.0 Canary. 

Some extra debugging that might help me:

In a dev profile or otherwise (backup your settings first!), try these extensions and see if they are broken. They are builds between 3.6.0 and 3.7.0.

about:addons > Gear icon > Install Add-on From File

- https://github.com/gyng/save-in/releases/download/v3.6.0/save_in_-3.6.0.zip
- [save_in_-9a3aa2e4e337f917ed3e327f6659871db33b8d86.zip](https://github.com/gyng/save-in/files/10726508/save_in_-9a3aa2e4e337f917ed3e327f6659871db33b8d86.zip)
- [save_in_-35b32d59921f5884698aecc272d2acf4198a4130.zip](https://github.com/gyng/save-in/files/10726509/save_in_-35b32d59921f5884698aecc272d2acf4198a4130.zip)
- [save_in_-3aa3c98e207adb714271db3a17d3616a0935a6ec.zip](https://github.com/gyng/save-in/files/10726510/save_in_-3aa3c98e207adb714271db3a17d3616a0935a6ec.zip)

**Comment by gyng** [comment]
@seth-rah I've updated Chrome to 3.7.1, pending approval. Here's hoping it fixes the issue. If I can't replicate the issue I will rollback published versions to 3.6.0, if possible.

**Comment by seth-rah** [comment]
Thanks

I'll have a look tomorrow to see if the problem is solved

**Comment by seth-rah** [comment]
Can confirm that updating to 3.7.1 has resolved the issue
