### ISSUE TITLE
Add submenus for nested directories

### ISSUE THREAD

**Issue by gyng** [gyng/save-in#26]
Will have to parse, combine nested subdirectories, and hook them up using `parentId`.

See: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/menus/create#Parameters

**Comment by tombones** [comment]
Just here to bump this request, because it's the main feature I'm missing from pre-Quantum imagesave plugins. I frequently sort folders into a directory with 20 subfolders, and having all of those on the root level of the menu is impractical. Being able to show subdirectories (or even just configure manual submenus in the extension) would be a huge boon for productivity.

**Comment by gyng** [comment]
I've added submenus in v3.1.0. On Windows at least, the submenu itself cannot be clicked.

```
animals
>mammals
>>i/cats
>>i/dogs
```

**Comment by GallaherMike** [comment]
So trying this out with 3.1.2 on Chrome. There seems to be a bug with the third layer all getting combined.

cars
>american
>>ford
>>dodge
>italian
>>maserati 
>>alfa romeo

puts ford, dodge, maserati, and alfa romeo all under american. so it looks like the third level is not tracking the parent correctly.

**Comment by gyng** [comment]
Thanks for reporting. This is a really hairy bit of old code that I repurposed so I must apologise for the bugs. v3.1.3 should fix this.

**Comment by tombones** [comment]
Thanks so much for adding this and aliasing. I can now use this almost exactly like my pre-quantum save extensions now. Is there a tip jar where I can send a donation for your great work?

**Comment by gyng** [comment]
Thanks, but no tip jar for now, at least! Reporting bugs and filing issues is more than sufficient help.
