### ISSUE TITLE
Chrome settings not saving.

### ISSUE THREAD

**Issue by ZzzZombi** [gyng/save-in#76]
No problem on Firefox Nightly. Using Chrome Dev, none of the settings are saved upon quitting the settings page.

Is there a "Save" button that I'm missing? On Firefox it just saves as you change parameters.

**Comment by gyng** [comment]
I'll investigate this. It seems to be saving on my Chrome 67 stable, which version are you on?

**Comment by DanaMW** [comment]
Thank you for the Update friend (just putting it here for  you see it)

**Comment by gyng** [comment]
@DanaMW thanks for the support. Are you encountering this issue as well? If so, can you share your Chrome version?

**Comment by DanaMW** [comment]
Your more than welcome. I use this programs many many times a day every day  lol. And yes as I told you a While back my chrome (Version 69.0.3486.0 (Official Build) dev (64-bit)) has been doing it. I just read in an export on use for now.

**Comment by DanaMW** [comment]
I use a fair amount of scripts and style files in Tamper and Stylus (Another great program) so I will do  a complete clean out and conflict  test this morning for us.

**Comment by gyng** [comment]
I still can't replicate any issue in Windows Version 69.0.3486.0 (Official Build) dev (64-bit).

This is on a fresh install of both the extension and Chrome Dev. I'll try it on another OS once I get access to it.

It'll be great if anyone is able to post any error logs (extension details > inspect background page and the Errors in the top level). I'm wondering if this is caused by bad settings or the like.

**Comment by ZzzZombi** [comment]
Sorry for taking so long to reply.

Issue seems to be solved for now and been working for a few days now, no problem.

I'm using Chrome Dev Version 69.0.3486.

I don't know how exactly it started saving the settings but all I did was selecting and deselecting some setting parameters' checkboxes (so it shows that green confirmation icon). That's it.

Other wild guess of mine, could it be a windows permission problem? For example Chrome.exe not having privileges to write to the extension's config file.

**Comment by gyng** [comment]
@ZzzZombi thanks for the logs and the update, and do feel free to report if you notice anything wrong again. Sometimes the new versions have breaking changes that need fixing before they hit stable. Since I don't use Nightly/Canary as my daily drivers I don't have advance warning of when things will break.

I don't know what exactly happened in this case, but it'll be annoying if it keeps happening.

**Comment by ZzzZombi** [comment]
@gyng No problem. I guess let's just say it's one of those "very rare, weird, only applies to a specific case" kind of bug. I'll make sure to report any future problems. And thanks for this essential extension.

**Comment by DanaMW** [comment]
Uncaught (in promise) TypeError: Illegal invocation: Function must be called on an object of type StorageArea
    at resolve (chrome-polyfill.js:11)
    at new Promise (<anonymous>)
    at Object._promisify [as get] (chrome-polyfill.js:10)
    at Object.OptionsManagement.loadOptions (option.js:128)
    at window.init (index.js:11)
    at index.js:322

**Comment by DanaMW** [comment]
still not saving ... that was in your Ext background page

**Comment by gyng** [comment]
Thanks for the error. That looks like a problem with my own polyfill. I've been waiting for mozilla/webextension-polyfill to release 0.3.0 (which they just did!), so I'll see if I can get that integrated instead.

**Comment by DanaMW** [comment]
Very cool. That was the latest Chrome Dev
Google Chrome is up to date
Version 69.0.3493.3 (Official Build) dev (64-bit
Thanks again for sticking with us :)

**Comment by gyng** [comment]
I've published 2.7.2 for Chrome which uses Mozilla's polyfill. I can't replicate the issue locally so I can't tell if this will fix your issue, so please take a look.
